// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykfrcjnyqyqelqcuxiee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrZnJjam55cXlxZWxxY3V4aWVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMTg5NDEsImV4cCI6MjA2NTg5NDk0MX0.ISy7qQ3hKVvuXzHhe1_oWz7eHJw2FmyFvV_7ZcsRZFo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);